<?
function GuthabensteuerungList() { return array(
"Phone_06603404350" => array(
         "OID" => 12676, 
         "Name" => "Phone_06603404350", 
         "Typ" => 3, 
         "Order" => "100", 
             	),
"Phone_06607625474" => array(
         "OID" => 38943, 
         "Name" => "Phone_06607625474", 
         "Typ" => 3, 
         "Order" => "102", 
             	),
"Phone_06602765645" => array(
         "OID" => 52832, 
         "Name" => "Phone_06602765645", 
         "Typ" => 3, 
         "Order" => "104", 
             	),
"Phone_06603192670" => array(
         "OID" => 55857, 
         "Name" => "Phone_06603192670", 
         "Typ" => 3, 
         "Order" => "106", 
             	),
"Phone_06605325076" => array(
         "OID" => 32717, 
         "Name" => "Phone_06605325076", 
         "Typ" => 3, 
         "Order" => "108", 
             	),
"Phone_06603404332" => array(
         "OID" => 34178, 
         "Name" => "Phone_06603404332", 
         "Typ" => 3, 
         "Order" => "110", 
             	),
"Phone_06605960456" => array(
         "OID" => 48743, 
         "Name" => "Phone_06605960456", 
         "Typ" => 3, 
         "Order" => "112", 
             	),
"Phone_06607845067" => array(
         "OID" => 31273, 
         "Name" => "Phone_06607845067", 
         "Typ" => 3, 
         "Order" => "114", 
             	),
"Phone_06602980747" => array(
         "OID" => 35594, 
         "Name" => "Phone_06602980747", 
         "Typ" => 3, 
         "Order" => "116", 
             	),
"Phone_06763242665" => array(
         "OID" => 36535, 
         "Name" => "Phone_06763242665", 
         "Typ" => 3, 
         "Order" => "118", 
             	),

      );}

function AmisStromverbrauchList() { return array(
"Server_Wirkenergie" => array(
         "OID" => 29257, 
         "Name" => "Server_Wirkenergie", 
         "Typ"      => 2, 
         "Profile"  => "~Electricity", 
         "Order"    => "100", 
             	),
"Server_Wirkleistung" => array(
         "OID" => 26534, 
         "Name" => "Server_Wirkleistung", 
         "Typ"      => 2, 
         "Profile"  => "~Power", 
         "Order"    => "101", 
             	),
"Ladestation_Wirkenergie" => array(
         "OID" => 40933, 
         "Name" => "Ladestation_Wirkenergie", 
         "Typ"      => 2, 
         "Profile"  => "~Electricity", 
         "Order"    => "102", 
             	),
"Ladestation_Wirkleistung" => array(
         "OID" => 32325, 
         "Name" => "Ladestation_Wirkleistung", 
         "Typ"      => 2, 
         "Profile"  => "~Power", 
         "Order"    => "103", 
             	),
"Boiler_Wirkenergie" => array(
         "OID" => 29362, 
         "Name" => "Boiler_Wirkenergie", 
         "Typ"      => 2, 
         "Profile"  => "~Electricity", 
         "Order"    => "104", 
             	),
"Boiler_Wirkleistung" => array(
         "OID" => 32379, 
         "Name" => "Boiler_Wirkleistung", 
         "Typ"      => 2, 
         "Profile"  => "~Power", 
         "Order"    => "105", 
             	),
"Feuchtigkeit_Wirkenergie" => array(
         "OID" => 28404, 
         "Name" => "Feuchtigkeit_Wirkenergie", 
         "Typ"      => 2, 
         "Profile"  => "~Electricity", 
         "Order"    => "106", 
             	),
"Feuchtigkeit_Wirkleistung" => array(
         "OID" => 49550, 
         "Name" => "Feuchtigkeit_Wirkleistung", 
         "Typ"      => 2, 
         "Profile"  => "~Power", 
         "Order"    => "107", 
             	),
"Gartenbeleuchtung_Wirkenergie" => array(
         "OID" => 31288, 
         "Name" => "Gartenbeleuchtung_Wirkenergie", 
         "Typ"      => 2, 
         "Profile"  => "~Electricity", 
         "Order"    => "108", 
             	),
"Gartenbeleuchtung_Wirkleistung" => array(
         "OID" => 54096, 
         "Name" => "Gartenbeleuchtung_Wirkleistung", 
         "Typ"      => 2, 
         "Profile"  => "~Power", 
         "Order"    => "109", 
             	),
"GartenbeleuchtungOst_Wirkenergie" => array(
         "OID" => 17361, 
         "Name" => "GartenbeleuchtungOst_Wirkenergie", 
         "Typ"      => 2, 
         "Profile"  => "~Electricity", 
         "Order"    => "110", 
             	),
"GartenbeleuchtungOst_Wirkleistung" => array(
         "OID" => 40357, 
         "Name" => "GartenbeleuchtungOst_Wirkleistung", 
         "Typ"      => 2, 
         "Profile"  => "~Power", 
         "Order"    => "111", 
             	),
"AZ_Effektlicht_Wirkenergie" => array(
         "OID" => 11328, 
         "Name" => "AZ_Effektlicht_Wirkenergie", 
         "Typ"      => 2, 
         "Profile"  => "~Electricity", 
         "Order"    => "112", 
             	),
"AZ_Effektlicht_Wirkleistung" => array(
         "OID" => 30751, 
         "Name" => "AZ_Effektlicht_Wirkleistung", 
         "Typ"      => 2, 
         "Profile"  => "~Power", 
         "Order"    => "113", 
             	),
"WohnzimmerHeizung_Wirkenergie" => array(
         "OID" => 27755, 
         "Name" => "WohnzimmerHeizung_Wirkenergie", 
         "Typ"      => 2, 
         "Profile"  => "~Electricity", 
         "Order"    => "114", 
             	),
"WohnzimmerHeizung_Wirkleistung" => array(
         "OID" => 45762, 
         "Name" => "WohnzimmerHeizung_Wirkleistung", 
         "Typ"      => 2, 
         "Profile"  => "~Power", 
         "Order"    => "115", 
             	),
"ArbeitszimmerHeizung_Wirkenergie" => array(
         "OID" => 27054, 
         "Name" => "ArbeitszimmerHeizung_Wirkenergie", 
         "Typ"      => 2, 
         "Profile"  => "~Electricity", 
         "Order"    => "116", 
             	),
"ArbeitszimmerHeizung_Wirkleistung" => array(
         "OID" => 50951, 
         "Name" => "ArbeitszimmerHeizung_Wirkleistung", 
         "Typ"      => 2, 
         "Profile"  => "~Power", 
         "Order"    => "117", 
             	),
"KellerzimmerHeizung_Wirkenergie" => array(
         "OID" => 37830, 
         "Name" => "KellerzimmerHeizung_Wirkenergie", 
         "Typ"      => 2, 
         "Profile"  => "~Electricity", 
         "Order"    => "118", 
             	),
"KellerzimmerHeizung_Wirkleistung" => array(
         "OID" => 34196, 
         "Name" => "KellerzimmerHeizung_Wirkleistung", 
         "Typ"      => 2, 
         "Profile"  => "~Power", 
         "Order"    => "119", 
             	),
"ArbeitszimmerRouter_Wirkenergie" => array(
         "OID" => 40790, 
         "Name" => "ArbeitszimmerRouter_Wirkenergie", 
         "Typ"      => 2, 
         "Profile"  => "~Electricity", 
         "Order"    => "120", 
             	),
"ArbeitszimmerRouter_Wirkleistung" => array(
         "OID" => 32269, 
         "Name" => "ArbeitszimmerRouter_Wirkleistung", 
         "Typ"      => 2, 
         "Profile"  => "~Power", 
         "Order"    => "121", 
             	),

      );}

function SysInfoList() { return array(
"Hostname" => array(
         "OID" => 35146, 
         "Name" => "Hostname", 
         "Typ"      => 3, 
         "Profile"  => "", 
         "Order"    => "200", 
             	),
"Betriebssystemname" => array(
         "OID" => 39862, 
         "Name" => "Betriebssystemname", 
         "Typ"      => 3, 
         "Profile"  => "", 
         "Order"    => "201", 
             	),
"Betriebssystemversion" => array(
         "OID" => 23386, 
         "Name" => "Betriebssystemversion", 
         "Typ"      => 3, 
         "Profile"  => "", 
         "Order"    => "202", 
             	),
"Hotfix" => array(
         "OID" => 49154, 
         "Name" => "Hotfix", 
         "Typ"      => 3, 
         "Profile"  => "", 
         "Order"    => "203", 
             	),
"ExternalIP" => array(
         "OID" => 49943, 
         "Name" => "ExternalIP", 
         "Typ"      => 3, 
         "Profile"  => "", 
         "Order"    => "204", 
             	),
"IPS_UpTime" => array(
         "OID" => 49898, 
         "Name" => "IPS_UpTime", 
         "Typ"      => 3, 
         "Profile"  => "", 
         "Order"    => "205", 
             	),
"IPS_Version" => array(
         "OID" => 55022, 
         "Name" => "IPS_Version", 
         "Typ"      => 3, 
         "Profile"  => "", 
         "Order"    => "206", 
             	),

      );}

function ROID_List() { return array(
"LBG70-2Virt" => array(
         "Adresse" => "http://wolfgangjoebstl@yahoo.com:Cloudg06@wolfgangjoebstl.synology.me:3876/api/", 
         "VisRootID" => "35687", 
         "WebFront" => "36315", 
         "Administrator" => "30569", 
         "RemoteAccess" => "43362", 
         "ServerName" => "15320", 
         "Temperatur" => "19326", 
         "Schalter" => "50523", 
         "Kontakte" => "31408", 
         "Taster" => "41106", 
         "Bewegung" => "13599", 
         "HeatControl" => "50914", 
         "HeatSet" => "30635", 
         "Humidity" => "26904", 
         "SysInfo" => "59960", 
         "Andere" => "48641", 
         "ArchiveHandler" => "27926", 
             	),
      );}

?>