<?
function ParamList() {
		return array(
"GiessAnlage" => array("OID"     => '34359',
                       "Name"    => 'GiessAnlage',
                       "Type"    => '1',
                       "Profile" => 'GiessAnlagenProfil'),
"GiessKreis" => array("OID"     => '45879',
                       "Name"    => 'GiessKreis',
                       "Type"    => '1',
                       "Profile" => 'GiessKreisProfil'),
"GiessTime" => array("OID"     => '32501',
                       "Name"    => 'GiessTime',
                       "Type"    => '1',
                       "Profile" => 'Minuten'),
"GiessTimeRemain" => array("OID"     => '54847',
                       "Name"    => 'GiessTimeRemain',
                       "Type"    => '1',
                       "Profile" => 'Minuten'),
"GiessKreisInfo" => array("OID"     => '15644',
                       "Name"    => 'GiessKreisInfo',
                       "Type"    => '3',
                       "Profile" => '~HTMLBox'),
"GiessDauerInfo" => array("OID"     => '28281',
                       "Name"    => 'GiessDauerInfo',
                       "Type"    => '3',
                       "Profile" => '~HTMLBox'),
"GiessCount" => array("OID"     => '56786',
                       "Name"    => 'GiessCount',
                       "Type"    => '1',
                       "Profile" => ''),
"GiessCountOffset" => array("OID"     => '53518',
                       "Name"    => 'GiessCountOffset',
                       "Type"    => '1',
                       "Profile" => ''),
"GiessPause" => array("OID"     => '16166',
                       "Name"    => 'GiessPause',
                       "Type"    => '1',
                       "Profile" => 'Minuten'),
"GiessAnlagePrev" => array("OID"     => '54033',
                       "Name"    => 'GiessAnlagePrev',
                       "Type"    => '1',
                       "Profile" => ''),
"Nachricht_Garten_Input" => array("OID"     => '34591',
                       "Name"    => 'Nachricht_Garten_Input',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile01" => array("OID"     => '46740',
                       "Name"    => 'Nachricht_Garten_Zeile01',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile02" => array("OID"     => '10993',
                       "Name"    => 'Nachricht_Garten_Zeile02',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile03" => array("OID"     => '36967',
                       "Name"    => 'Nachricht_Garten_Zeile03',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile04" => array("OID"     => '40035',
                       "Name"    => 'Nachricht_Garten_Zeile04',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile05" => array("OID"     => '31919',
                       "Name"    => 'Nachricht_Garten_Zeile05',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile06" => array("OID"     => '38117',
                       "Name"    => 'Nachricht_Garten_Zeile06',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile07" => array("OID"     => '37367',
                       "Name"    => 'Nachricht_Garten_Zeile07',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile08" => array("OID"     => '57674',
                       "Name"    => 'Nachricht_Garten_Zeile08',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile09" => array("OID"     => '56983',
                       "Name"    => 'Nachricht_Garten_Zeile09',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile10" => array("OID"     => '41596',
                       "Name"    => 'Nachricht_Garten_Zeile10',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile11" => array("OID"     => '13908',
                       "Name"    => 'Nachricht_Garten_Zeile11',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile12" => array("OID"     => '28592',
                       "Name"    => 'Nachricht_Garten_Zeile12',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile13" => array("OID"     => '15270',
                       "Name"    => 'Nachricht_Garten_Zeile13',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile14" => array("OID"     => '14820',
                       "Name"    => 'Nachricht_Garten_Zeile14',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile15" => array("OID"     => '55396',
                       "Name"    => 'Nachricht_Garten_Zeile15',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile16" => array("OID"     => '44173',
                       "Name"    => 'Nachricht_Garten_Zeile16',
                       "Type"    => '3',
                       "Profile" => ''),
);
}
?>