<?
function ParamList() {
		return array(
"GiessAnlage" => array("OID"     => '51335',
                       "Name"    => 'GiessAnlage',
                       "Type"    => '1',
                       "Profile" => 'GiessAnlagenProfil'),
"GiessKreis" => array("OID"     => '29908',
                       "Name"    => 'GiessKreis',
                       "Type"    => '1',
                       "Profile" => 'GiessKreisProfil'),
"GiessStartzeitpunkt" => array("OID"     => '16311',
                       "Name"    => 'GiessStartzeitpunkt',
                       "Type"    => '0',
                       "Profile" => 'GiessConfigProfil'),
"GiessAnlage" => array("OID"     => '51335',
                       "Name"    => 'GiessAnlage',
                       "Type"    => '1',
                       "Profile" => 'GiessAnlagenProfil'),
"GiessKreis" => array("OID"     => '29908',
                       "Name"    => 'GiessKreis',
                       "Type"    => '1',
                       "Profile" => 'GiessKreisProfil'),
"GiessTime" => array("OID"     => '49574',
                       "Name"    => 'GiessTime',
                       "Type"    => '1',
                       "Profile" => 'Minuten'),
"GiessTimeRemain" => array("OID"     => '24725',
                       "Name"    => 'GiessTimeRemain',
                       "Type"    => '1',
                       "Profile" => 'Minuten'),
"GiessKreisInfo" => array("OID"     => '46041',
                       "Name"    => 'GiessKreisInfo',
                       "Type"    => '3',
                       "Profile" => '~HTMLBox'),
"GiessDauerInfo" => array("OID"     => '48921',
                       "Name"    => 'GiessDauerInfo',
                       "Type"    => '3',
                       "Profile" => '~HTMLBox'),
"GiessCount" => array("OID"     => '52361',
                       "Name"    => 'GiessCount',
                       "Type"    => '1',
                       "Profile" => ''),
"GiessCountOffset" => array("OID"     => '14167',
                       "Name"    => 'GiessCountOffset',
                       "Type"    => '1',
                       "Profile" => ''),
"GiessPause" => array("OID"     => '48665',
                       "Name"    => 'GiessPause',
                       "Type"    => '1',
                       "Profile" => 'Minuten'),
"GiessAnlagePrev" => array("OID"     => '30378',
                       "Name"    => 'GiessAnlagePrev',
                       "Type"    => '1',
                       "Profile" => ''),
);
}
?>