<?
function ParamList() {
		return array(
"GiessAnlage" => array("OID"     => '53590',
                       "Name"    => 'GiessAnlage',
                       "Type"    => '1',
                       "Profile" => 'GiessAnlagenProfil'),
"GiessCount" => array("OID"     => '34779',
                       "Name"    => 'GiessCount',
                       "Type"    => '1',
                       "Profile" => ''),
"GiessAnlagePrev" => array("OID"     => '43777',
                       "Name"    => 'GiessAnlagePrev',
                       "Type"    => '1',
                       "Profile" => ''),
"GiessTime" => array("OID"     => '59097',
                       "Name"    => 'GiessTime',
                       "Type"    => '1',
                       "Profile" => ''),
"Nachricht_Garten_Input" => array("OID"     => '46179',
                       "Name"    => 'Nachricht_Garten_Input',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile01" => array("OID"     => '41894',
                       "Name"    => 'Nachricht_Garten_Zeile01',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile02" => array("OID"     => '17852',
                       "Name"    => 'Nachricht_Garten_Zeile02',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile03" => array("OID"     => '27537',
                       "Name"    => 'Nachricht_Garten_Zeile03',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile04" => array("OID"     => '57943',
                       "Name"    => 'Nachricht_Garten_Zeile04',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile05" => array("OID"     => '37566',
                       "Name"    => 'Nachricht_Garten_Zeile05',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile06" => array("OID"     => '32745',
                       "Name"    => 'Nachricht_Garten_Zeile06',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile07" => array("OID"     => '44585',
                       "Name"    => 'Nachricht_Garten_Zeile07',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile08" => array("OID"     => '52108',
                       "Name"    => 'Nachricht_Garten_Zeile08',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile09" => array("OID"     => '41598',
                       "Name"    => 'Nachricht_Garten_Zeile09',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile10" => array("OID"     => '59066',
                       "Name"    => 'Nachricht_Garten_Zeile10',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile11" => array("OID"     => '57299',
                       "Name"    => 'Nachricht_Garten_Zeile11',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile12" => array("OID"     => '27357',
                       "Name"    => 'Nachricht_Garten_Zeile12',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile13" => array("OID"     => '50109',
                       "Name"    => 'Nachricht_Garten_Zeile13',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile14" => array("OID"     => '27668',
                       "Name"    => 'Nachricht_Garten_Zeile14',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile15" => array("OID"     => '11747',
                       "Name"    => 'Nachricht_Garten_Zeile15',
                       "Type"    => '3',
                       "Profile" => ''),
"Nachricht_Garten_Zeile16" => array("OID"     => '54625',
                       "Name"    => 'Nachricht_Garten_Zeile16',
                       "Type"    => '3',
                       "Profile" => ''),
);
}
?>