<?
function HomematicInstanzen() { return array(
"HomeMatic Socket" => array(
         "CONFIG" => '{"Open":0,"Host":"10.0.1.33","Port":5545,"RFOpen":true,"RFPort":2001,"WROpen":false,"WRPort":2000,"IPOpen":true,"IPPort":2010,"IPAddress":"10.0.1.8"}', 
             	),
);}

function FHTList() { return array(
);}
function FS20List() { return array(
);}
function HomematicList() { return array(
"Keller-Boiler-Schaltgeraet" => array(
         "OID" => 43516, 
         "Adresse" => "MEQ0420910:1", 
         "Name" => "Keller-Boiler-Schaltgeraet", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "STATE" => array(
                              "OID" => "59471", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "20897", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "31149", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Kellertechnik-GartenEffektlicht1" => array(
         "OID" => 51772, 
         "Adresse" => "LEQ0282158:3", 
         "Name" => "Kellertechnik-GartenEffektlicht1", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "WORKING" => array(
                              "OID" => "23282", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "42414", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "39290", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
             	),
      	),
"Keller-ServerSchalter" => array(
         "OID" => 43604, 
         "Adresse" => "LEQ1316022:1", 
         "Name" => "Keller-ServerSchalter", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "46306", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "31512", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "10489", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Keller-Boiler-Messgeraet" => array(
         "OID" => 40679, 
         "Adresse" => "MEQ0420910:2", 
         "Name" => "Keller-Boiler-Messgeraet", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "ENERGY_COUNTER" => array(
                              "OID" => "23996", 
                              "Name" => "ENERGY_COUNTER", 
                              "Typ" => "2",), 
                "BOOT" => array(
                              "OID" => "20263", 
                              "Name" => "BOOT", 
                              "Typ" => "2",), 
                "CURRENT" => array(
                              "OID" => "44045", 
                              "Name" => "CURRENT", 
                              "Typ" => "2",), 
                "FREQUENCY" => array(
                              "OID" => "35767", 
                              "Name" => "FREQUENCY", 
                              "Typ" => "2",), 
                "POWER" => array(
                              "OID" => "26717", 
                              "Name" => "POWER", 
                              "Typ" => "2",), 
                "VOLTAGE" => array(
                              "OID" => "10410", 
                              "Name" => "VOLTAGE", 
                              "Typ" => "2",), 
             	),
      	),
"Sensor-Wintergarten" => array(
         "OID" => 18521, 
         "Adresse" => "JEQ0218184:1", 
         "Name" => "Sensor-Wintergarten", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "HUMIDITY" => array(
                              "OID" => "43733", 
                              "Name" => "HUMIDITY", 
                              "Typ" => "2",), 
                "TEMPERATURE" => array(
                              "OID" => "32505", 
                              "Name" => "TEMPERATURE", 
                              "Typ" => "2",), 
             	),
      	),
"Wintergarten-Taster-5" => array(
         "OID" => 39578, 
         "Adresse" => "LEQ0984089:5", 
         "Name" => "Wintergarten-Taster-5", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "PRESS_LONG" => array(
                              "OID" => "15795", 
                              "Name" => "PRESS_LONG", 
                              "Typ" => "2",), 
                "INSTALL_TEST" => array(
                              "OID" => "18794", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "PRESS_CONT" => array(
                              "OID" => "24975", 
                              "Name" => "PRESS_CONT", 
                              "Typ" => "2",), 
                "PRESS_LONG_RELEASE" => array(
                              "OID" => "18851", 
                              "Name" => "PRESS_LONG_RELEASE", 
                              "Typ" => "2",), 
                "PRESS_SHORT" => array(
                              "OID" => "13532", 
                              "Name" => "PRESS_SHORT", 
                              "Typ" => "2",), 
             	),
      	),
"Kellerzimmer-Licht" => array(
         "OID" => 41052, 
         "Adresse" => "MEQ0324513:1", 
         "Name" => "Kellerzimmer-Licht", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "STATE" => array(
                              "OID" => "14815", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "28078", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "19455", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Sensor-Kellerzimmer" => array(
         "OID" => 50030, 
         "Adresse" => "JEQ0654602:1", 
         "Name" => "Sensor-Kellerzimmer", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "HUMIDITY" => array(
                              "OID" => "35169", 
                              "Name" => "HUMIDITY", 
                              "Typ" => "2",), 
                "TEMPERATURE" => array(
                              "OID" => "17490", 
                              "Name" => "TEMPERATURE", 
                              "Typ" => "2",), 
             	),
      	),
"Keller-LadestationMessgeraet" => array(
         "OID" => 55007, 
         "Adresse" => "LEQ0536013:2", 
         "Name" => "Keller-LadestationMessgeraet", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "VOLTAGE" => array(
                              "OID" => "24729", 
                              "Name" => "VOLTAGE", 
                              "Typ" => "2",), 
                "POWER" => array(
                              "OID" => "29140", 
                              "Name" => "POWER", 
                              "Typ" => "2",), 
                "ENERGY_COUNTER" => array(
                              "OID" => "32228", 
                              "Name" => "ENERGY_COUNTER", 
                              "Typ" => "2",), 
                "BOOT" => array(
                              "OID" => "28697", 
                              "Name" => "BOOT", 
                              "Typ" => "2",), 
                "CURRENT" => array(
                              "OID" => "39649", 
                              "Name" => "CURRENT", 
                              "Typ" => "2",), 
                "FREQUENCY" => array(
                              "OID" => "32458", 
                              "Name" => "FREQUENCY", 
                              "Typ" => "2",), 
             	),
      	),
"Bewegung-Stiegenabgang " => array(
         "OID" => 36925, 
         "Adresse" => "KEQ0365190:1", 
         "Name" => "Bewegung-Stiegenabgang ", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "ERROR" => array(
                              "OID" => "22583", 
                              "Name" => "ERROR", 
                              "Typ" => "2",), 
                "INSTALL_TEST" => array(
                              "OID" => "16513", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "BRIGHTNESS" => array(
                              "OID" => "29385", 
                              "Name" => "BRIGHTNESS", 
                              "Typ" => "2",), 
                "MOTION" => array(
                              "OID" => "18613", 
                              "Name" => "MOTION", 
                              "Typ" => "2",), 
             	),
      	),
"Keller-ServerMessgeraet" => array(
         "OID" => 34447, 
         "Adresse" => "LEQ1316022:2", 
         "Name" => "Keller-ServerMessgeraet", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "VOLTAGE" => array(
                              "OID" => "36099", 
                              "Name" => "VOLTAGE", 
                              "Typ" => "2",), 
                "CURRENT" => array(
                              "OID" => "33745", 
                              "Name" => "CURRENT", 
                              "Typ" => "2",), 
                "BOOT" => array(
                              "OID" => "13559", 
                              "Name" => "BOOT", 
                              "Typ" => "2",), 
                "ENERGY_COUNTER" => array(
                              "OID" => "53194", 
                              "Name" => "ENERGY_COUNTER", 
                              "Typ" => "2",), 
                "FREQUENCY" => array(
                              "OID" => "37768", 
                              "Name" => "FREQUENCY", 
                              "Typ" => "2",), 
                "POWER" => array(
                              "OID" => "51394", 
                              "Name" => "POWER", 
                              "Typ" => "2",), 
             	),
      	),
"Kellerabgang-Bewegung" => array(
         "OID" => 23614, 
         "Adresse" => "JEQ0702179:1", 
         "Name" => "Kellerabgang-Bewegung", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "MOTION" => array(
                              "OID" => "36365", 
                              "Name" => "MOTION", 
                              "Typ" => "2",), 
                "INSTALL_TEST" => array(
                              "OID" => "42226", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "BRIGHTNESS" => array(
                              "OID" => "40192", 
                              "Name" => "BRIGHTNESS", 
                              "Typ" => "2",), 
             	),
      	),
"Sensor-Keller" => array(
         "OID" => 58862, 
         "Adresse" => "JEQ0218144:1", 
         "Name" => "Sensor-Keller", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "HUMIDITY" => array(
                              "OID" => "28635", 
                              "Name" => "HUMIDITY", 
                              "Typ" => "2",), 
                "TEMPERATURE" => array(
                              "OID" => "57353", 
                              "Name" => "TEMPERATURE", 
                              "Typ" => "2",), 
             	),
      	),
"SchalterGang-rechts" => array(
         "OID" => 27424, 
         "Adresse" => "IEQ0026272:2", 
         "Name" => "SchalterGang-rechts", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "STATE" => array(
                              "OID" => "18762", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "47451", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "41271", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Kellerzimmer-Bewegung" => array(
         "OID" => 16349, 
         "Adresse" => "KEQ0844709:1", 
         "Name" => "Kellerzimmer-Bewegung", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INSTALL_TEST" => array(
                              "OID" => "26786", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "ERROR" => array(
                              "OID" => "41435", 
                              "Name" => "ERROR", 
                              "Typ" => "2",), 
                "MOTION" => array(
                              "OID" => "17427", 
                              "Name" => "MOTION", 
                              "Typ" => "2",), 
                "BRIGHTNESS" => array(
                              "OID" => "55331", 
                              "Name" => "BRIGHTNESS", 
                              "Typ" => "2",), 
             	),
      	),
"Garten-Dusche-Taster-2" => array(
         "OID" => 55535, 
         "Adresse" => "LEQ1099970:2", 
         "Name" => "Garten-Dusche-Taster-2", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INSTALL_TEST" => array(
                              "OID" => "26996", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "PRESS_CONT" => array(
                              "OID" => "39021", 
                              "Name" => "PRESS_CONT", 
                              "Typ" => "2",), 
                "PRESS_SHORT" => array(
                              "OID" => "35692", 
                              "Name" => "PRESS_SHORT", 
                              "Typ" => "2",), 
                "PRESS_LONG" => array(
                              "OID" => "13570", 
                              "Name" => "PRESS_LONG", 
                              "Typ" => "2",), 
                "PRESS_LONG_RELEASE" => array(
                              "OID" => "44265", 
                              "Name" => "PRESS_LONG_RELEASE", 
                              "Typ" => "2",), 
             	),
      	),
"Sensor-Kellerlager" => array(
         "OID" => 52512, 
         "Adresse" => "JEQ0218252:1", 
         "Name" => "Sensor-Kellerlager", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "HUMIDITY" => array(
                              "OID" => "50057", 
                              "Name" => "HUMIDITY", 
                              "Typ" => "2",), 
                "TEMPERATURE" => array(
                              "OID" => "57892", 
                              "Name" => "TEMPERATURE", 
                              "Typ" => "2",), 
             	),
      	),
"Garten-Teichpumpe-Schalter" => array(
         "OID" => 40684, 
         "Adresse" => "KEQ0037180:1", 
         "Name" => "Garten-Teichpumpe-Schalter", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "STATE" => array(
                              "OID" => "28813", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "31689", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "16845", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
             	),
      	),
"Sensor-Wohnzimmer" => array(
         "OID" => 36699, 
         "Adresse" => "JEQ0654379:1", 
         "Name" => "Sensor-Wohnzimmer", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "TEMPERATURE" => array(
                              "OID" => "10565", 
                              "Name" => "TEMPERATURE", 
                              "Typ" => "2",), 
                "HUMIDITY" => array(
                              "OID" => "38884", 
                              "Name" => "HUMIDITY", 
                              "Typ" => "2",), 
             	),
      	),
"TorAufZuImpuls" => array(
         "OID" => 46944, 
         "Adresse" => "JEQ0568041:3", 
         "Name" => "TorAufZuImpuls", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "19703", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "42613", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "23014", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Sensor-Aussennische" => array(
         "OID" => 24431, 
         "Adresse" => "JEQ0267627:1", 
         "Name" => "Sensor-Aussennische", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "HUMIDITY" => array(
                              "OID" => "31669", 
                              "Name" => "HUMIDITY", 
                              "Typ" => "2",), 
                "TEMPERATURE" => array(
                              "OID" => "28662", 
                              "Name" => "TEMPERATURE", 
                              "Typ" => "2",), 
             	),
      	),
"Kontakt Tuere-Wintergarten" => array(
         "OID" => 27845, 
         "Adresse" => "LEQ1059995:1", 
         "Name" => "Kontakt Tuere-Wintergarten", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "ERROR" => array(
                              "OID" => "54527", 
                              "Name" => "ERROR", 
                              "Typ" => "2",), 
                "INSTALL_TEST" => array(
                              "OID" => "29127", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "LOWBAT" => array(
                              "OID" => "44239", 
                              "Name" => "LOWBAT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "32135", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
             	),
      	),
"ReservePort4" => array(
         "OID" => 15363, 
         "Adresse" => "JEQ0568041:4", 
         "Name" => "ReservePort4", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "42781", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "11710", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "50018", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Kueche-Rolladensteuerung" => array(
         "OID" => 29761, 
         "Adresse" => "KEQ0047634:1", 
         "Name" => "Kueche-Rolladensteuerung", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "DIRECTION" => array(
                              "OID" => "40341", 
                              "Name" => "DIRECTION", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "10546", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "LEVEL" => array(
                              "OID" => "45643", 
                              "Name" => "LEVEL", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "39028", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"SchalterGang-links" => array(
         "OID" => 53650, 
         "Adresse" => "IEQ0026272:1", 
         "Name" => "SchalterGang-links", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "STATE" => array(
                              "OID" => "53809", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "25614", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "37306", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Kueche-Zusatzlicht" => array(
         "OID" => 36328, 
         "Adresse" => "KEQ1076465:1", 
         "Name" => "Kueche-Zusatzlicht", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "24083", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "50795", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "22114", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Wohnzimmer-Ventilator" => array(
         "OID" => 36184, 
         "Adresse" => "JEQ0568041:2", 
         "Name" => "Wohnzimmer-Ventilator", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "STATE" => array(
                              "OID" => "49941", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "28012", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "14153", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Wintergarten-Taster-2" => array(
         "OID" => 39733, 
         "Adresse" => "LEQ0984089:2", 
         "Name" => "Wintergarten-Taster-2", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "PRESS_LONG_RELEASE" => array(
                              "OID" => "19761", 
                              "Name" => "PRESS_LONG_RELEASE", 
                              "Typ" => "2",), 
                "INSTALL_TEST" => array(
                              "OID" => "25619", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "PRESS_CONT" => array(
                              "OID" => "43080", 
                              "Name" => "PRESS_CONT", 
                              "Typ" => "2",), 
                "PRESS_LONG" => array(
                              "OID" => "52211", 
                              "Name" => "PRESS_LONG", 
                              "Typ" => "2",), 
                "PRESS_SHORT" => array(
                              "OID" => "39142", 
                              "Name" => "PRESS_SHORT", 
                              "Typ" => "2",), 
             	),
      	),
"Badezimmer-Zusatzheizung" => array(
         "OID" => 19105, 
         "Adresse" => "MEQ0071624:1", 
         "Name" => "Badezimmer-Zusatzheizung", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "36564", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "32751", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "45849", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Sensor-Arbeitszimmer" => array(
         "OID" => 41381, 
         "Adresse" => "JEQ0217973:1", 
         "Name" => "Sensor-Arbeitszimmer", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "TEMPERATURE" => array(
                              "OID" => "11646", 
                              "Name" => "TEMPERATURE", 
                              "Typ" => "2",), 
                "HUMIDITY" => array(
                              "OID" => "26261", 
                              "Name" => "HUMIDITY", 
                              "Typ" => "2",), 
             	),
      	),
"Keller-Entfeuchter-Messgeraet" => array(
         "OID" => 41291, 
         "Adresse" => "LEQ0529790:2", 
         "Name" => "Keller-Entfeuchter-Messgeraet", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "BOOT" => array(
                              "OID" => "20594", 
                              "Name" => "BOOT", 
                              "Typ" => "2",), 
                "CURRENT" => array(
                              "OID" => "44974", 
                              "Name" => "CURRENT", 
                              "Typ" => "2",), 
                "POWER" => array(
                              "OID" => "33447", 
                              "Name" => "POWER", 
                              "Typ" => "2",), 
                "ENERGY_COUNTER" => array(
                              "OID" => "49204", 
                              "Name" => "ENERGY_COUNTER", 
                              "Typ" => "2",), 
                "FREQUENCY" => array(
                              "OID" => "18506", 
                              "Name" => "FREQUENCY", 
                              "Typ" => "2",), 
                "VOLTAGE" => array(
                              "OID" => "37500", 
                              "Name" => "VOLTAGE", 
                              "Typ" => "2",), 
             	),
      	),
"Licht-Kueche-Stiegenabgang" => array(
         "OID" => 59771, 
         "Adresse" => "KEQ1074646:1", 
         "Name" => "Licht-Kueche-Stiegenabgang", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "STATE" => array(
                              "OID" => "23882", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "10666", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "27624", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
             	),
      	),
"Kellertechnik-GartenVentil2" => array(
         "OID" => 30569, 
         "Adresse" => "LEQ0282158:2", 
         "Name" => "Kellertechnik-GartenVentil2", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "WORKING" => array(
                              "OID" => "33482", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "11207", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "53367", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
             	),
      	),
"Wintergarten-Taster-6" => array(
         "OID" => 11598, 
         "Adresse" => "LEQ0984089:6", 
         "Name" => "Wintergarten-Taster-6", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INSTALL_TEST" => array(
                              "OID" => "54489", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "PRESS_CONT" => array(
                              "OID" => "53255", 
                              "Name" => "PRESS_CONT", 
                              "Typ" => "2",), 
                "PRESS_LONG" => array(
                              "OID" => "16329", 
                              "Name" => "PRESS_LONG", 
                              "Typ" => "2",), 
                "PRESS_SHORT" => array(
                              "OID" => "33886", 
                              "Name" => "PRESS_SHORT", 
                              "Typ" => "2",), 
                "PRESS_LONG_RELEASE" => array(
                              "OID" => "44828", 
                              "Name" => "PRESS_LONG_RELEASE", 
                              "Typ" => "2",), 
             	),
      	),
"Bewegung-Aussen" => array(
         "OID" => 32762, 
         "Adresse" => "LEQ0658657:1", 
         "Name" => "Bewegung-Aussen", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "MOTION" => array(
                              "OID" => "11422", 
                              "Name" => "MOTION", 
                              "Typ" => "2",), 
                "BRIGHTNESS" => array(
                              "OID" => "37924", 
                              "Name" => "BRIGHTNESS", 
                              "Typ" => "2",), 
                "INSTALL_TEST" => array(
                              "OID" => "11032", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
             	),
      	),
"Wohnzimer Stehlampe Dimmer" => array(
         "OID" => 22459, 
         "Adresse" => "HEQ0353497:1", 
         "Name" => "Wohnzimer Stehlampe Dimmer", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "LEVEL" => array(
                              "OID" => "41387", 
                              "Name" => "LEVEL", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "33640", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "32187", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
                "DIRECTION" => array(
                              "OID" => "40608", 
                              "Name" => "DIRECTION", 
                              "Typ" => "2",), 
                "ERROR_OVERHEAT" => array(
                              "OID" => "45357", 
                              "Name" => "ERROR_OVERHEAT", 
                              "Typ" => "2",), 
                "ERROR_OVERLOAD" => array(
                              "OID" => "35807", 
                              "Name" => "ERROR_OVERLOAD", 
                              "Typ" => "2",), 
                "ERROR_REDUCED" => array(
                              "OID" => "48410", 
                              "Name" => "ERROR_REDUCED", 
                              "Typ" => "2",), 
             	),
      	),
"Keller-Entfeuchter-Schalter" => array(
         "OID" => 49878, 
         "Adresse" => "LEQ0529790:1", 
         "Name" => "Keller-Entfeuchter-Schalter", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "33022", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "40979", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "53408", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Bewegung Wohnzimmer-Eingang" => array(
         "OID" => 17347, 
         "Adresse" => "HEQ0406282:1", 
         "Name" => "Bewegung Wohnzimmer-Eingang", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "BRIGHTNESS" => array(
                              "OID" => "17130", 
                              "Name" => "BRIGHTNESS", 
                              "Typ" => "2",), 
                "ERROR" => array(
                              "OID" => "53961", 
                              "Name" => "ERROR", 
                              "Typ" => "2",), 
                "INSTALL_TEST" => array(
                              "OID" => "48486", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "MOTION" => array(
                              "OID" => "12529", 
                              "Name" => "MOTION", 
                              "Typ" => "2",), 
             	),
      	),
"Wintergarten-Taster-1" => array(
         "OID" => 16205, 
         "Adresse" => "LEQ0984089:1", 
         "Name" => "Wintergarten-Taster-1", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "PRESS_CONT" => array(
                              "OID" => "32863", 
                              "Name" => "PRESS_CONT", 
                              "Typ" => "2",), 
                "INSTALL_TEST" => array(
                              "OID" => "51077", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "PRESS_SHORT" => array(
                              "OID" => "44741", 
                              "Name" => "PRESS_SHORT", 
                              "Typ" => "2",), 
                "PRESS_LONG" => array(
                              "OID" => "45420", 
                              "Name" => "PRESS_LONG", 
                              "Typ" => "2",), 
                "PRESS_LONG_RELEASE" => array(
                              "OID" => "58362", 
                              "Name" => "PRESS_LONG_RELEASE", 
                              "Typ" => "2",), 
             	),
      	),
"Kontakt Tuere-Keller" => array(
         "OID" => 27979, 
         "Adresse" => "JEQ0715058:1", 
         "Name" => "Kontakt Tuere-Keller", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "STATE" => array(
                              "OID" => "50033", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "ERROR" => array(
                              "OID" => "41542", 
                              "Name" => "ERROR", 
                              "Typ" => "2",), 
                "INSTALL_TEST" => array(
                              "OID" => "37561", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "LOWBAT" => array(
                              "OID" => "34034", 
                              "Name" => "LOWBAT", 
                              "Typ" => "2",), 
             	),
      	),
"Wetterstation" => array(
         "OID" => 21963, 
         "Adresse" => "JEQ0735876:1", 
         "Name" => "Wetterstation", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "WIND_DIRECTION" => array(
                              "OID" => "43545", 
                              "Name" => "WIND_DIRECTION", 
                              "Typ" => "2",), 
                "RAINING" => array(
                              "OID" => "22560", 
                              "Name" => "RAINING", 
                              "Typ" => "2",), 
                "HUMIDITY" => array(
                              "OID" => "34471", 
                              "Name" => "HUMIDITY", 
                              "Typ" => "2",), 
                "BRIGHTNESS" => array(
                              "OID" => "40140", 
                              "Name" => "BRIGHTNESS", 
                              "Typ" => "2",), 
                "RAIN_COUNTER" => array(
                              "OID" => "20417", 
                              "Name" => "RAIN_COUNTER", 
                              "Typ" => "2",), 
                "SUNSHINEDURATION" => array(
                              "OID" => "44824", 
                              "Name" => "SUNSHINEDURATION", 
                              "Typ" => "2",), 
                "TEMPERATURE" => array(
                              "OID" => "32443", 
                              "Name" => "TEMPERATURE", 
                              "Typ" => "2",), 
                "WIND_DIRECTION_RANGE" => array(
                              "OID" => "27263", 
                              "Name" => "WIND_DIRECTION_RANGE", 
                              "Typ" => "2",), 
                "WIND_SPEED" => array(
                              "OID" => "13004", 
                              "Name" => "WIND_SPEED", 
                              "Typ" => "2",), 
             	),
      	),
"Garten-Beleuchtung-Schalter" => array(
         "OID" => 47212, 
         "Adresse" => "LEQ0529786:1", 
         "Name" => "Garten-Beleuchtung-Schalter", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "29138", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "45361", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "57747", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Gartenpumpe" => array(
         "OID" => 37228, 
         "Adresse" => "JEQ0568197:2", 
         "Name" => "Gartenpumpe", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "WORKING" => array(
                              "OID" => "56683", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "39058", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "31561", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
             	),
      	),
"Keller-LadestationSchalter" => array(
         "OID" => 45043, 
         "Adresse" => "LEQ0536013:1", 
         "Name" => "Keller-LadestationSchalter", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "STATE" => array(
                              "OID" => "11661", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "51395", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "23039", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Wintergarten-Taster-4" => array(
         "OID" => 49610, 
         "Adresse" => "LEQ0984089:4", 
         "Name" => "Wintergarten-Taster-4", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "PRESS_SHORT" => array(
                              "OID" => "35596", 
                              "Name" => "PRESS_SHORT", 
                              "Typ" => "2",), 
                "PRESS_CONT" => array(
                              "OID" => "19282", 
                              "Name" => "PRESS_CONT", 
                              "Typ" => "2",), 
                "INSTALL_TEST" => array(
                              "OID" => "14547", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "PRESS_LONG" => array(
                              "OID" => "16742", 
                              "Name" => "PRESS_LONG", 
                              "Typ" => "2",), 
                "PRESS_LONG_RELEASE" => array(
                              "OID" => "28233", 
                              "Name" => "PRESS_LONG_RELEASE", 
                              "Typ" => "2",), 
             	),
      	),
"Reserve2Port4" => array(
         "OID" => 51048, 
         "Adresse" => "JEQ0568197:4", 
         "Name" => "Reserve2Port4", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "14396", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "27324", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "34781", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
             	),
      	),
"Garten-Beleuchtung-Messgeraet" => array(
         "OID" => 46737, 
         "Adresse" => "LEQ0529786:2", 
         "Name" => "Garten-Beleuchtung-Messgeraet", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "POWER" => array(
                              "OID" => "28514", 
                              "Name" => "POWER", 
                              "Typ" => "2",), 
                "BOOT" => array(
                              "OID" => "58274", 
                              "Name" => "BOOT", 
                              "Typ" => "2",), 
                "CURRENT" => array(
                              "OID" => "22707", 
                              "Name" => "CURRENT", 
                              "Typ" => "2",), 
                "ENERGY_COUNTER" => array(
                              "OID" => "27821", 
                              "Name" => "ENERGY_COUNTER", 
                              "Typ" => "2",), 
                "FREQUENCY" => array(
                              "OID" => "47874", 
                              "Name" => "FREQUENCY", 
                              "Typ" => "2",), 
                "VOLTAGE" => array(
                              "OID" => "53488", 
                              "Name" => "VOLTAGE", 
                              "Typ" => "2",), 
             	),
      	),
"Wohnzimmer-Lichtblende" => array(
         "OID" => 54710, 
         "Adresse" => "JEQ0568041:1", 
         "Name" => "Wohnzimmer-Lichtblende", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "11833", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "57452", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "43327", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Kellertechnik-Gartenventil1" => array(
         "OID" => 16979, 
         "Adresse" => "LEQ0282158:1", 
         "Name" => "Kellertechnik-Gartenventil1", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "WORKING" => array(
                              "OID" => "40912", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "34856", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "39969", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
             	),
      	),
"Wintergarten-Beleuchtung" => array(
         "OID" => 13732, 
         "Adresse" => "MEQ0071690:1", 
         "Name" => "Wintergarten-Beleuchtung", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "15165", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "29987", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "55290", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"KellerlagerKlima-Schalter" => array(
         "OID" => 55173, 
         "Adresse" => "LEQ1316022:1", 
         "Name" => "KellerlagerKlima-Schalter", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "STATE" => array(
                              "OID" => "33064", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "18886", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "12251", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Kellertechnik-GartenEffektlicht2" => array(
         "OID" => 19974, 
         "Adresse" => "LEQ0282158:4", 
         "Name" => "Kellertechnik-GartenEffektlicht2", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "50673", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "53351", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "33721", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
             	),
      	),
"Wohnzimer Esstisch Dimmer" => array(
         "OID" => 15668, 
         "Adresse" => "KEQ0002712:1", 
         "Name" => "Wohnzimer Esstisch Dimmer", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "LEVEL" => array(
                              "OID" => "50942", 
                              "Name" => "LEVEL", 
                              "Typ" => "2",), 
                "DIRECTION" => array(
                              "OID" => "29868", 
                              "Name" => "DIRECTION", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "17981", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
                "ERROR_OVERHEAT" => array(
                              "OID" => "56687", 
                              "Name" => "ERROR_OVERHEAT", 
                              "Typ" => "2",), 
                "INHIBIT" => array(
                              "OID" => "39493", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "ERROR_REDUCED" => array(
                              "OID" => "36013", 
                              "Name" => "ERROR_REDUCED", 
                              "Typ" => "2",), 
                "ERROR_OVERLOAD" => array(
                              "OID" => "24956", 
                              "Name" => "ERROR_OVERLOAD", 
                              "Typ" => "2",), 
             	),
      	),
"Wintergarten-Taster-3" => array(
         "OID" => 10715, 
         "Adresse" => "LEQ0984089:3", 
         "Name" => "Wintergarten-Taster-3", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "PRESS_CONT" => array(
                              "OID" => "59908", 
                              "Name" => "PRESS_CONT", 
                              "Typ" => "2",), 
                "INSTALL_TEST" => array(
                              "OID" => "47304", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "PRESS_LONG" => array(
                              "OID" => "16222", 
                              "Name" => "PRESS_LONG", 
                              "Typ" => "2",), 
                "PRESS_LONG_RELEASE" => array(
                              "OID" => "29570", 
                              "Name" => "PRESS_LONG_RELEASE", 
                              "Typ" => "2",), 
                "PRESS_SHORT" => array(
                              "OID" => "52221", 
                              "Name" => "PRESS_SHORT", 
                              "Typ" => "2",), 
             	),
      	),
"Garten-Dusche-Taster-1" => array(
         "OID" => 22763, 
         "Adresse" => "LEQ1099970:1", 
         "Name" => "Garten-Dusche-Taster-1", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INSTALL_TEST" => array(
                              "OID" => "51715", 
                              "Name" => "INSTALL_TEST", 
                              "Typ" => "2",), 
                "PRESS_LONG_RELEASE" => array(
                              "OID" => "18768", 
                              "Name" => "PRESS_LONG_RELEASE", 
                              "Typ" => "2",), 
                "PRESS_CONT" => array(
                              "OID" => "55503", 
                              "Name" => "PRESS_CONT", 
                              "Typ" => "2",), 
                "PRESS_LONG" => array(
                              "OID" => "23025", 
                              "Name" => "PRESS_LONG", 
                              "Typ" => "2",), 
                "PRESS_SHORT" => array(
                              "OID" => "45771", 
                              "Name" => "PRESS_SHORT", 
                              "Typ" => "2",), 
             	),
      	),
"Gartensteckdosen" => array(
         "OID" => 14368, 
         "Adresse" => "JEQ0568197:3", 
         "Name" => "Gartensteckdosen", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "38780", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "26812", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "12900", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Steuerung Wintergarten Strom" => array(
         "OID" => 20960, 
         "Adresse" => "JEQ0295375:1", 
         "Name" => "Steuerung Wintergarten Strom", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "54708", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "29851", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "40453", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
             	),
      	),
"Licht-Kellerabgang" => array(
         "OID" => 39543, 
         "Adresse" => "JEQ0568197:1", 
         "Name" => "Licht-Kellerabgang", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "INHIBIT" => array(
                              "OID" => "53763", 
                              "Name" => "INHIBIT", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "30006", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "WORKING" => array(
                              "OID" => "20289", 
                              "Name" => "WORKING", 
                              "Typ" => "2",), 
             	),
      	),
"Effektlicht:Schalter" => array(
         "OID" => 23455, 
         "Adresse" => "0001D3C98DD823:3", 
         "Name" => "Effektlicht:Schalter", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "PROCESS" => array(
                              "OID" => "48338", 
                              "Name" => "PROCESS", 
                              "Typ" => "2",), 
                "STATE" => array(
                              "OID" => "52448", 
                              "Name" => "STATE", 
                              "Typ" => "2",), 
                "SECTION" => array(
                              "OID" => "33668", 
                              "Name" => "SECTION", 
                              "Typ" => "2",), 
             	),
      	),
"Effektlicht:Energie" => array(
         "OID" => 52612, 
         "Adresse" => "0001D3C98DD823:6", 
         "Name" => "Effektlicht:Energie", 
         "CCU" => "HomeMatic Socket", 
         "COID" => array(
                "POWER" => array(
                              "OID" => "10953", 
                              "Name" => "POWER", 
                              "Typ" => "2",), 
                "FREQUENCY" => array(
                              "OID" => "39766", 
                              "Name" => "FREQUENCY", 
                              "Typ" => "2",), 
                "ENERGY_COUNTER" => array(
                              "OID" => "33450", 
                              "Name" => "ENERGY_COUNTER", 
                              "Typ" => "2",), 
                "VOLTAGE" => array(
                              "OID" => "51676", 
                              "Name" => "VOLTAGE", 
                              "Typ" => "2",), 
                "CURRENT" => array(
                              "OID" => "36790", 
                              "Name" => "CURRENT", 
                              "Typ" => "2",), 
                "ENERGY_COUNTER_OVERFLOW" => array(
                              "OID" => "34867", 
                              "Name" => "ENERGY_COUNTER_OVERFLOW", 
                              "Typ" => "2",), 
             	),
      	),
);}

?>